/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    building?: string;
                    floor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpotSearchResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spots/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    id?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpotItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CsrfTokenResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OccurrenceListItem"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOccurrenceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OccurrenceDetail"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OccurrenceDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/occurrences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OccurrenceDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveOccurrenceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OccurrenceDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceValidationProblem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceConflictOfOccurrenceDetail"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryListDetail"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveCategoriesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryListDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceValidationProblem"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceConflictOfCategoryListDetail"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spots/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    building?: string;
                    floor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpotSearchResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spots/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpotDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query: {
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveSpotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpotDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceValidationProblem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceConflictOfSpotDetail"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    occurrenceId?: string;
                    publication?: string;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventListItem"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEventRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetail"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DraftValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEventRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DraftValidationProblem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventConflict"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminRef: {
            /** Format: uuid */
            id: string;
            displayName: string;
        };
        CategoryDraft: {
            /** Format: uuid */
            id: string;
            name: null | string;
            selectable: boolean;
        };
        CategoryItem: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            sortOrder: number;
            selectable: boolean;
        };
        CategoryListDetail: {
            /** Format: int64 */
            rowVersion: number;
            /** Format: date-time */
            updatedAt: null | string;
            updatedBy: null | components["schemas"]["EditorRef"];
            publication: string;
            items: components["schemas"]["CategoryListItem"][];
        };
        CategoryListItem: {
            /** Format: uuid */
            id: string;
            name: string;
            selectable: boolean;
            /** Format: int32 */
            referenceCount: number;
        };
        CreateEventRequest: {
            /** Format: uuid */
            operationId: string;
            draft: null | components["schemas"]["EventDraft"];
        };
        CreateOccurrenceRequest: {
            /** Format: uuid */
            operationId: string;
            draft: null | components["schemas"]["OccurrenceDraft"];
        };
        CsrfTokenResponse: {
            token: string;
        };
        DraftProblem: {
            path: string;
            code: string;
            message: string;
        };
        DraftValidationProblem: {
            code: string;
            title: string;
            problems: components["schemas"]["DraftProblem"][];
        };
        EditorRef: {
            /** Format: uuid */
            id: string;
            displayName: string;
        };
        EventConflict: {
            code: string;
            title: string;
            latest: components["schemas"]["EventDetail"];
        };
        EventDetail: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            rowVersion: number;
            /** Format: uuid */
            revisionId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: components["schemas"]["AdminRef"];
            publication: string;
            draft: components["schemas"]["EventDraft"];
        };
        EventDraft: {
            schemaVersion: string;
            title: null | string;
            description: null | string;
            /** Format: uuid */
            categoryId: null | string;
            /** Format: uuid */
            occurrenceId: null | string;
            slots: components["schemas"]["EventSlot"][];
        };
        EventListItem: {
            /** Format: uuid */
            id: string;
            title: null | string;
            /** Format: uuid */
            occurrenceId: null | string;
            /** Format: int32 */
            slotCount: number;
            /** Format: int32 */
            venueCount: number;
            slots: components["schemas"]["EventSlotSummary"][];
            publication: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: components["schemas"]["AdminRef"];
        };
        EventSlot: {
            /** Format: uuid */
            slotId: string;
            /** Format: uuid */
            ocDayId: null | string;
            timeMode: null | string;
            fixed: null | components["schemas"]["FixedTime"];
            participation: null | string;
            status: string;
            cancelNote: null | string;
            venues: components["schemas"]["SlotVenue"][];
        };
        EventSlotSummary: {
            /** Format: date */
            date: null | string;
            timeMode: null | string;
            start: null | string;
            end: null | string;
            status: string;
            dayCancelled: boolean;
        };
        FixedTime: {
            start: null | string;
            end: null | string;
        };
        LoginRequest: {
            email: null | string;
            password: null | string;
        };
        OccurrenceDetail: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            rowVersion: number;
            /** Format: date-time */
            updatedAt: null | string;
            updatedBy: null | components["schemas"]["EditorRef"];
            publication: string;
            draft: components["schemas"]["OccurrenceDraft"];
            references: components["schemas"]["SlotReference"][];
        };
        OccurrenceDraft: {
            name: null | string;
            sourceNote: null | string;
            days: components["schemas"]["OcDayDraft"][];
        };
        OccurrenceItem: {
            /** Format: uuid */
            id: string;
            name: string;
            days: components["schemas"]["OcDayItem"][];
        };
        OccurrenceListItem: {
            /** Format: uuid */
            id: string;
            name: string;
            days: components["schemas"]["OcDayItem"][];
            /** Format: int32 */
            relatedEventCount: number;
            publication: string;
            /** Format: date-time */
            updatedAt: null | string;
            updatedBy: null | components["schemas"]["EditorRef"];
        };
        OcDayDraft: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            date: null | string;
            publicStart: null | string;
            publicEnd: null | string;
            status: string;
            cancelNote: null | string;
        };
        OcDayItem: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            date: string;
            publicStart: null | string;
            publicEnd: null | string;
            status: string;
        };
        ReferenceConflictOfCategoryListDetail: {
            code: string;
            title: string;
            latest: null | components["schemas"]["CategoryListDetail"];
        };
        ReferenceConflictOfOccurrenceDetail: {
            code: string;
            title: string;
            latest: null | components["schemas"]["OccurrenceDetail"];
        };
        ReferenceConflictOfSpotDetail: {
            code: string;
            title: string;
            latest: null | components["schemas"]["SpotDetail"];
        };
        ReferenceData: {
            occurrences: components["schemas"]["OccurrenceItem"][];
            categories: components["schemas"]["CategoryItem"][];
        };
        ReferenceValidationProblem: {
            code: string;
            title: string;
            problems: components["schemas"]["DraftProblem"][];
        };
        SaveCategoriesRequest: {
            /** Format: uuid */
            operationId: string;
            /** Format: int64 */
            rowVersion: number;
            items: null | components["schemas"]["CategoryDraft"][];
        };
        SaveOccurrenceRequest: {
            /** Format: uuid */
            operationId: string;
            /** Format: int64 */
            rowVersion: number;
            draft: null | components["schemas"]["OccurrenceDraft"];
        };
        SaveSpotRequest: {
            /** Format: uuid */
            operationId: string;
            /** Format: int64 */
            rowVersion: number;
            draft: null | components["schemas"]["SpotDraft"];
        };
        SessionResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: string;
            environmentLabel: null | string;
        };
        SlotReference: {
            /** Format: uuid */
            eventId: string;
            eventTitle: null | string;
            /** Format: uuid */
            slotId: string;
            /** Format: uuid */
            ocDayId: null | string;
            timeMode: null | string;
            start: null | string;
            end: null | string;
            slotStatus: string;
        };
        SlotVenue: {
            canonicalSpotId: string;
            note: null | string;
        };
        SpotDetail: {
            canonicalId: string;
            /** Format: int64 */
            rowVersion: number;
            /** Format: date-time */
            updatedAt: null | string;
            updatedBy: null | components["schemas"]["EditorRef"];
            isPublished: boolean;
            draft: components["schemas"]["SpotDraft"];
            placement: components["schemas"]["SpotPlacement"];
            draftEvents: components["schemas"]["SpotEventReference"][];
        };
        SpotDraft: {
            name: null | string;
            aliases: string[];
            utilization: string;
        };
        SpotEventReference: {
            /** Format: uuid */
            eventId: string;
            eventTitle: null | string;
            /** Format: int32 */
            slotCount: number;
        };
        SpotItem: {
            canonicalId: string;
            name: string;
            aliases: string[];
            buildingName: null | string;
            floorName: null | string;
            isPublished: boolean;
            utilization: string;
        };
        SpotPlacement: {
            buildingName: null | string;
            floorName: null | string;
        };
        SpotSearchResult: {
            /** Format: int32 */
            totalCount: number;
            items: components["schemas"]["SpotItem"][];
            buildings: string[];
            floors: string[];
        };
        UpdateEventRequest: {
            /** Format: uuid */
            operationId: string;
            /** Format: int64 */
            rowVersion: number;
            draft: null | components["schemas"]["EventDraft"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
