// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudioApi.Data;

#nullable disable

namespace StudioApi.Migrations
{
    [DbContext(typeof(StudioDbContext))]
    [Migration("20260924084017_AddRestoreAndLogOrdering")]
    partial class AddRestoreAndLogOrdering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("studio")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("admin_claims", "studio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("admin_logins", "studio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("admin_tokens", "studio");
                });

            modelBuilder.Entity("StudioApi.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Selectable")
                        .HasColumnType("boolean")
                        .HasColumnName("selectable");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("categories", "studio");
                });

            modelBuilder.Entity("StudioApi.Models.CategoryListState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_revision_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("category_list_state", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_category_list_state_singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RowVersion = 1L
                        });
                });

            modelBuilder.Entity("StudioApi.Models.EventHead", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_revision_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("EventId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("event_heads", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_event_heads_row_version", "row_version > 0");
                        });
                });

            modelBuilder.Entity("StudioApi.Models.EventRevision", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<Guid?>("BaseRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_revision_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("RevisionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_revisions_operation_id");

                    b.HasIndex("EventId", "CreatedAt")
                        .HasDatabaseName("ix_event_revisions_event_id_created_at");

                    b.ToTable("event_revisions", "studio");
                });

            modelBuilder.Entity("StudioApi.Models.MapDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("map_datasets", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_map_datasets_checksum", "length(checksum) = 64");

                            t.HasCheckConstraint("ck_map_datasets_status", "status IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("ck_map_datasets_version", "version > 0");
                        });
                });

            modelBuilder.Entity("StudioApi.Models.OcDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancelNote")
                        .HasColumnType("text")
                        .HasColumnName("cancel_note");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("occurrence_id");

                    b.Property<TimeOnly?>("PublicEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("public_end");

                    b.Property<TimeOnly?>("PublicStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("public_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_oc_days_occurrence_id_date");

                    b.ToTable("oc_days", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_oc_days_status", "status IN ('normal', 'cancelled')");
                        });
                });

            modelBuilder.Entity("StudioApi.Models.Occurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_revision_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("SourceNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_note");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("occurrences", "studio");
                });

            modelBuilder.Entity("StudioApi.Models.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long>("StartedAtMs")
                        .HasColumnType("bigint")
                        .HasColumnName("started_at_ms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.Property<string>("TargetLabel")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target_label");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_operation_logs_operation_id")
                        .HasFilter("operation_id IS NOT NULL");

                    b.HasIndex("StartedAtMs")
                        .HasDatabaseName("ix_operation_logs_started_at_ms");

                    b.ToTable("operation_logs", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_operation_logs_action", "action IN ('save', 'import', 'publish', 'signIn', 'signInFailed', 'signOut')");

                            t.HasCheckConstraint("ck_operation_logs_status", "status IN ('processing', 'succeeded', 'failed')");
                        });
                });

            modelBuilder.Entity("StudioApi.Models.Publication", b =>
                {
                    b.Property<string>("TargetKind")
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TargetKind", "TargetId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("publications", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_publications_state", "state IN ('published', 'withdrawn')");

                            t.HasCheckConstraint("ck_publications_target_kind", "target_kind IN ('event', 'occurrence', 'categories', 'spot')");
                        });
                });

            modelBuilder.Entity("StudioApi.Models.ReferenceRevision", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.HasKey("RevisionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_reference_revisions_operation_id")
                        .HasFilter("operation_id IS NOT NULL");

                    b.HasIndex("Kind", "TargetId", "CreatedAt")
                        .HasDatabaseName("ix_reference_revisions_target");

                    b.ToTable("reference_revisions", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_reference_revisions_kind", "kind IN ('occurrence', 'categories', 'spot')");

                            t.HasCheckConstraint("ck_reference_revisions_source", "source IN ('editor', 'import', 'restore')");
                        });
                });

            modelBuilder.Entity("StudioApi.Models.Release", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid?>("ValidationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("validation_run_id");

                    b.HasKey("ReleaseId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_releases_operation_id")
                        .HasFilter("operation_id IS NOT NULL");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_releases_sequence");

                    b.HasIndex("ValidationRunId");

                    b.ToTable("releases", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_releases_source", "source IN ('studio', 'import')");
                        });
                });

            modelBuilder.Entity("StudioApi.Models.ReleaseEntry", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("TargetKind")
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("label");

                    b.Property<Guid?>("PreviousRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_revision_id");

                    b.Property<Guid?>("RestoredFromRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("restored_from_revision_id");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<Guid?>("StashedRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("stashed_revision_id");

                    b.HasKey("ReleaseId", "TargetKind", "TargetId");

                    b.HasIndex("TargetKind", "TargetId")
                        .HasDatabaseName("ix_release_entries_target");

                    b.ToTable("release_entries", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_release_entries_action", "action IN ('publish', 'withdraw', 'restore')");

                            t.HasCheckConstraint("ck_release_entries_target_kind", "target_kind IN ('event', 'occurrence', 'categories', 'spot')");
                        });
                });

            modelBuilder.Entity("StudioApi.Models.Spot", b =>
                {
                    b.Property<string>("CanonicalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("canonical_id");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("building_name");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_revision_id");

                    b.Property<string>("FloorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("floor_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Utilization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utilization");

                    b.HasKey("CanonicalId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("spots", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_spots_utilization", "utilization IN ('available', 'noNewSelection', 'withdrawn')");
                        });
                });

            modelBuilder.Entity("StudioApi.Models.SpotNameAlias", b =>
                {
                    b.Property<string>("CanonicalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("canonical_id");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alias");

                    b.HasKey("CanonicalId", "Alias");

                    b.ToTable("spot_name_aliases", "studio");
                });

            modelBuilder.Entity("StudioApi.Models.StudioAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_normalized_user_name");

                    b.ToTable("admins", "studio");
                });

            modelBuilder.Entity("StudioApi.Models.ValidationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("entries");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("findings");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("validation_runs", "studio", t =>
                        {
                            t.HasCheckConstraint("ck_validation_runs_status", "status IN ('ok', 'failed')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioApi.Models.CategoryListState", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StudioApi.Models.EventHead", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioApi.Models.EventRevision", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioApi.Models.EventHead", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioApi.Models.OcDay", b =>
                {
                    b.HasOne("StudioApi.Models.Occurrence", null)
                        .WithMany("Days")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioApi.Models.Occurrence", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StudioApi.Models.OperationLog", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StudioApi.Models.Publication", b =>
                {
                    b.HasOne("StudioApi.Models.Release", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioApi.Models.ReferenceRevision", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StudioApi.Models.Release", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudioApi.Models.ValidationRun", null)
                        .WithMany()
                        .HasForeignKey("ValidationRunId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StudioApi.Models.ReleaseEntry", b =>
                {
                    b.HasOne("StudioApi.Models.Release", null)
                        .WithMany("Entries")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioApi.Models.Spot", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StudioApi.Models.SpotNameAlias", b =>
                {
                    b.HasOne("StudioApi.Models.Spot", null)
                        .WithMany("NameAliases")
                        .HasForeignKey("CanonicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioApi.Models.ValidationRun", b =>
                {
                    b.HasOne("StudioApi.Models.StudioAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioApi.Models.Occurrence", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("StudioApi.Models.Release", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("StudioApi.Models.Spot", b =>
                {
                    b.Navigation("NameAliases");
                });
#pragma warning restore 612, 618
        }
    }
}
